version: "3.2"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
        sh -c "./init.bash"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=database
      - DB_NAME=aapollo
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - database
  database:
    image: postgres:10-alpine
    restart: always
    expose:
      - 5432
    volumes: 
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=aapollo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword    
  redis:
    image: redis:alpine
    expose:
      - 6379
  celery:
    restart: always
    build:
      context: .
    command: celery -A main worker -l info
    volumes:
      - ./app:/app
    environment:
      - DB_HOST=redis
      - DB_NAME=aapollo
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - database
      - redis
      - app